# Generated by Django 5.0.3 on 2024-07-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicefinder', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
